eshop/category/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

urlpatterns = [
    path('' , views.test),
    path('laptops' , views.laptops_view ,  name='laptops'),
    path('phones' , views.phones_view ,  name='phones'),
    path('phone-info/<int:pk>/' ,  views.PhoneDetailView.as_view(),  name='phone-detail'),
    path('laptop-info/<int:pk>/', views.LaptopDetailView.as_view(), name='laptop-detail'),
    path('search', views.search, name='search'),
    path('source-detail-item/<int:id>', views.source_detail_item, name='source_detail_item'),
    path('add-to-backet/<int:id>/<str:category>/', views.add_to_backet, name='add-to-backet'),
    path('basket-list', views.basket_list, name='basket-list'),
    path('delete-from-basket/<int:id>/<str:category>/', views.delete_from_basket, name='delete-from-basket'),
]

eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('category.urls')),
    # path('backet/' , include('backet.urls' , namespace='backet')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()



from django.conf import settings

eshop/category/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

CHOICE_CATEGORY  = (
    ('laptops' , 'Ноутбуки'),
    ('mobile_phones' , 'Телефоны'),
    ('tablet' , 'Планшеты'),
    ('source_details' , 'Комплектующие'),
    ('nau' , 'Наушники')
)



class Category(models.Model):
    name = models.CharField(max_length=100 ,  verbose_name= 'Категория'  , choices=CHOICE_CATEGORY)

    def __str__(self):
        return self.name


OPERATION_SYSTEM = (
    ('mac' , 'MacOS'),
    ('linux' , 'Linux'),
    ('windows' , 'Windows')
)

TYPE_MONITOR  = (
    ('glossy'  , 'Глянцевый'),
    ('matt'  , 'Матовый')
)

class Laptop(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE , default=1)
    model =  models.CharField(max_length=255 , verbose_name='Модель ноутбука' , default='i534')
    brand =  models.CharField(max_length=255 , verbose_name='Бренд ' , default='Apple')
    diagonal =  models.CharField(max_length=255 , verbose_name='Диагональ ' , default='12')
    oper_system =  models.CharField(max_length=255 , verbose_name='Операционная система' , choices=OPERATION_SYSTEM)
    oper_memory = models.IntegerField(verbose_name='ОЗУ' , default=16)
    type_monitor = models.CharField(max_length=255 , verbose_name='Тип экрана' , choices=TYPE_MONITOR)
    count_core = models.IntegerField(verbose_name='Количество ядер' , default=8)
    price = models.IntegerField(verbose_name='Цена' , default='50000')
    image = models.ImageField(upload_to='images/', blank=True, null=True ,  verbose_name='Картинка')
    desc = models.TextField(max_length=500, verbose_name='Описание ', default='no desc' )

    def __str__(self):
        return 'Модель - {} Бренд - {}'.format(self.model , self.brand)

    def get_all(self):
        return Laptop.objects.all()

    def delete_all(self):
        return Laptop.objects.all().delete()



class Phone(models.Model):
    category  = models.ForeignKey(Category , on_delete=models.CASCADE , default=2)
    model = models.CharField(max_length=255 , verbose_name='Модель телефона')
    brand = models.CharField(max_length=255, verbose_name='Бренд ', default='Apple')
    oper_system = models.CharField(max_length=255, verbose_name='Операционная система', choices=OPERATION_SYSTEM)
    oper_memory = models.IntegerField(verbose_name='ОЗУ', default=16)
    count_core = models.IntegerField(verbose_name='Количество ядер', default=8)
    price = models.IntegerField(verbose_name='Цена', default='2000')
    image = models.ImageField(upload_to='images/', blank=True, null=True, verbose_name='Картинка')
    desc = models.TextField(max_length=500, verbose_name='Описание ', default='no desc')

    def __str__(self):
        return 'Модель - {} Бренд - {}'.format(self.model , self.brand)

class SourceDetail(models.Model):
    category  = models.ForeignKey(Category , on_delete=models.CASCADE , verbose_name="Комлектующие в категории")
    title = models.CharField(max_length=255 , verbose_name='Назва', default='')
    short_desc = models.CharField(max_length=255 , verbose_name='Краткое описание' , default='Краткое описание')
    image  = models.ImageField(upload_to='images/')
    price = models.FloatField()
    content  = RichTextUploadingField(default='')

    def __str__(self):
        return '{} {}'.format(self.title , self.short_desc)




class Basket(models.Model):
    name_category  = models.ForeignKey(Category , on_delete=models.CASCADE)
    product_id = models.IntegerField()

    def __str__(self):
        return str(self.product_id)

eshop/category/views.py
from django.shortcuts import render
from django.http import HttpResponse , JsonResponse
from .models import Laptop, Category, Phone, SourceDetail, Basket
from django.views.generic import DetailView

# from baсket.models import Basket
# from baсket.models import Backet


all_categories = Category.objects.all()
all_Baсket_len = len(Basket.objects.all())
# all_Baсket_len = None
category = None


def test(request):
    all_Baсket_len = len(Basket.objects.all())
    laptop_instance = Laptop()
    all_laptop = laptop_instance.get_all()
    # laptop_instance.delete_all()
    ctx = {}
    ctx['category_name'] = 'all'
    ctx['all_laptop'] = all_laptop
    ctx['all_Baсket_len'] = all_Baсket_len
    print(all_laptop)
    return render(request, 'category/index.html', ctx)


def laptops_view(request):
    ctx = {}
    all_laptops = Laptop.objects.all()
    all_categories = Category.objects.all()
    all_Baсket_len = len(Basket.objects.all())

    ctx['objects'] = all_laptops
    ctx['category_name'] = 'laptops'
    ctx['all_categories'] = all_categories
    ctx['title'] = 'Ноутбуки'
    ctx['all_Baсket_len'] = all_Baсket_len

    print(all_categories)
    for elem in all_categories:
        print(elem)
    # print(all_laptops)
    return render(request, 'category/laptops.html', ctx)


def phones_view(request):
    ctx = {}
    all_phones = Phone.objects.all()
    all_Baсket_len = len(Basket.objects.all())
    ctx['objects'] = all_phones
    ctx['category_name'] = 'mobile_phones'
    ctx['title'] = 'Телефони'
    ctx['all_Baсket_len'] = all_Baсket_len
    return render(request, 'category/phones.html', ctx)


class LaptopDetailView(DetailView):
    queryset = Laptop.objects.all()
    template_name = 'category/laptop_detail.html'


    def get_context_data(self, **kwargs):
        all_Baсket_len = len(Basket.objects.all())
        context = super(LaptopDetailView, self).get_context_data(**kwargs)
        try:
            source_detail = SourceDetail.objects.filter(category=Category.objects.get(name='laptops'))
            context['source_detail'] = source_detail
            print(source_detail)
        except:
            pass

        context['category_name'] = 'laptops'
        context['all_categories'] = all_categories
        context['all_Baсket_len'] = all_Baсket_len

        return context

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.save()
        return obj


class PhoneDetailView(DetailView):
    queryset = Phone.objects.all()
    template_name = 'category/laptop_detail.html'

    def get_context_data(self, **kwargs):
        all_Baсket_len = len(Basket.objects.all())
        context = super(PhoneDetailView, self).get_context_data(**kwargs)
        try:
            source_detail = SourceDetail.objects.filter(category=Category.objects.get(name='mobile_phones'))
            print(source_detail)
            context['source_detail'] = source_detail
        except:
            pass
        context['category_name'] = 'mobile_phones'
        context['all_categories'] = all_categories
        context['all_Baсket_len'] = all_Baсket_len
        return context

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.save()
        return obj


MODEL_CHOICE = {
    'laptops': Laptop,
}


def search(request):
    ctx = {}
    category = Category.objects.get(name=request.GET.get('category')).name
    all_Baсket_len = len(Basket.objects.all())
    if request.GET.get('to') == '' or request.GET.get('from') == '':
        all_search = MODEL_CHOICE[category].objects.all()
    else:
        all_search = MODEL_CHOICE[category].objects.all().filter(price__lt=request.GET.get('to'),
                                                                 price__gt=request.GET.get('from'))
    ctx['req_category'] = request.GET.get('category')
    ctx['req_price_to'] = request.GET.get('to')
    ctx['req_price_from'] = request.GET.get('from')
    ctx['all_search'] = all_search
    ctx['all_categories'] = all_categories
    ctx['category_name'] = category
    ctx['all_Baсket_len'] = all_Baсket_len
    return render(request, 'category/search.html', ctx)


def source_detail_item(request, id):
    all_Baсket_len = len(Basket.objects.all())
    object_source = SourceDetail.objects.get(id=id)
    ctx = {}
    ctx['object'] = object_source
    ctx['category_name'] = 'source_details'
    print(id)
    return render(request, 'category/source_detail_item.html', ctx)


def add_to_backet(request, id, category):
    target_category = Category.objects.get(name=category)
    Basket.objects.create(name_category=target_category , product_id=id)
    all_Baсket_len = len(Basket.objects.all())
    return JsonResponse({'len': all_Baсket_len
    })



def basket_list(request):
    laptops_category = Category.objects.get(name='laptops')
    mobiles_category = Category.objects.get(name='mobile_phones')
    ctx = {}
    laptops_in_basket  = Basket.objects.filter(name_category=laptops_category)
    list_laptops  = []
    for elem in laptops_in_basket:
        list_laptops.append(Laptop.objects.get(pk=elem.product_id))

    phones_in_basket = Basket.objects.filter(name_category=mobiles_category)
    list_phones = []
    for elem in phones_in_basket:
        list_phones.append(Phone.objects.get(pk=elem.product_id))

    all_Baсket_len = len(Basket.objects.all())
    ctx['all_Baсket_len'] = all_Baсket_len
    ctx['list_laptops'] = list_laptops
    ctx['list_phones'] = list_phones
    return render(request , 'category/basket_list.html' , ctx)



def delete_from_basket(request ,  id, category):
    ctx ={}
    target_category = Category.objects.get(name=category)
    Basket.objects.filter(name_category=target_category , product_id=id)[0].delete()
    ctx['ok'] = 'Success!'
    return JsonResponse({
        'ok' : 'Мы удалили с вашей корзины товар '
    })

eshop/eshop/templates/category/ajax_template.html
{% load static %}
<div class="basket-wrapper ">
    <h2>ноутбуки</h2>
    <div class="basket-item head">
        <p>Модель</p>
        <p>Бренд</p>
        <p>Діагональ</p>
        <p>Операционная система</p>
        <p>Оперативная память</p>
        <p>Тип монитора</p>
        <p>Цена , грн</p>
        <p></p>
        <p></p>
        <p></p>
    </div>

    {% for elem in list_laptops %}
    <div class="basket-item">

        <p>{{ elem.model }}</p>
        <p>{{ elem.brand }}</p>
        <p>{{ elem.diagonal }}</p>
        <p>{{ elem.oper_system }}</p>
        <p>{{ elem.oper_memory }}</p>
        <p>{{ elem.get_type_monitor_display }}</p>
        <p> {{ elem.price }} </p>
        <p><a href="{% url 'laptop-detail' elem.id %}">Детали</a></p>
        <p>
            <a class="js-deleting"  href="{% url 'delete-from-basket' elem.id elem.category %}">x</a>
        </p>
        <p>
            <a href="">
                <img width="40" class="heart-icon" src="{% static 'image/heart.png' %}" alt="">
            </a>
        </p>
    </div>
    {% endfor %}

</div>

<script>

    $(document).ready(function () {
        App.ajax.init();
    })


</script>

eshop/eshop/templates/category/basket_list.html
{% extends 'category/index.html' %}
{% load static %}
{% block content %}

<div class="ajax-wrapper">


    <div class="basket-wrapper ">
        {% if list_laptops %}
            <h2>ноутбуки</h2>
            <div class="basket-item head">
                <p>Модель</p>
                <p>Бренд</p>
                <p>Діагональ</p>
                <p>Операционная система</p>
                <p>Оперативная память</p>
                <p>Тип монитора</p>
                <p>Цена , грн</p>
                <p></p>
                <p></p>
                <p></p>
            </div>

            {% for elem in list_laptops %}
            <div class="basket-item">

                <p>{{ elem.model }}</p>
                <p>{{ elem.brand }}</p>
                <p>{{ elem.diagonal }}</p>
                <p>{{ elem.oper_system }}</p>
                <p>{{ elem.oper_memory }}</p>
                <p>{{ elem.get_type_monitor_display }}</p>
                <p> {{ elem.price }} </p>
                <p><a href="{% url 'laptop-detail' elem.id %}">Детали</a></p>
                <p>
                    <a class="js-deleting" href="{% url 'delete-from-basket' elem.id elem.category %}">x</a>
                </p>
                <p>
                    <a href="">
                        <img width="40" class="heart-icon" src="{% static 'image/heart.png' %}" alt="">
                    </a>
                </p>
            </div>
            {% endfor %}
        {% endif %}
        {% if list_phones %}
            <h2>Мобильные телефоны</h2>
            <div class="basket-item head">
                <p>Модель</p>
                <p>Бренд</p>
                <p>Операционная система</p>
                <p>Оперативная память</p>
                <p>Цена , грн</p>
                <p></p>
                <p></p>
                <p></p>
            </div>
            {% for elem in list_phones %}
            <div class="basket-item">

                <p>{{ elem.model }}</p>
                <p>{{ elem.brand }}</p>
                <p>{{ elem.oper_system }}</p>
                <p>{{ elem.oper_memory }}</p>
                <p> {{ elem.price }} </p>
                <p><a href="{% url 'phone-detail' elem.id %}">Детали</a></p>
                <p>
                    <a class="js-deleting" href="{% url 'delete-from-basket' elem.id elem.category %}">x</a>
                </p>
                <p>
                    <a href="">
                        <img width="40" class="heart-icon" src="{% static 'image/heart.png' %}" alt="">
                    </a>
                </p>
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
<span class="response-text"></span>
{% endblock %}


{% block extrascript  %}

<script>

    $(document).ready(function () {
        App.ajax.init();
    })


</script>
{% endblock  %}

eshop/eshop/templates/category/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="page-wrapper">
    {% include "includes/header.html" with a=5%}


    <section class="content">
        <div class="container">
            {% block content %}
                <div class="home-page">
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home phones">
                      <a class='inner-text' href="{% url 'phones' %}">Телефони</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                    <div class="item-home laptop">
                      <a class='inner-text' href="{% url 'laptops' %}">Ноутбуки</a>
                    </div>
                </div>
            {% endblock  %}
        </div>
    </section>
    {% block extrascript  %}
    {% endblock  %}
</div>
</body>
</html>

eshop/eshop/templates/category/item_product.html
{% load static %}
{% if object %}
    <div class="object-item" style="  margin-left: -70px;">
        {% if object.image %}
        <img  src="{{ object.image.url }}" alt="">
        {% endif  %}
        <div class="desc-item-wrap">
            <div class="desc-item">
                <div class="info-item">
                    <p class="left">Бренд</p>
                    <p class="right">{{ object.brand }}</p>
                </div>
                <div class="info-item">
                    <p class="left" >Модель</p>
                    <p class="right">{{ object.model }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Операционная система</p>
                    <p class="right">{{ object.oper_system }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Оперативная память</p>
                    <p class="right">{{ object.oper_memory }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Тип экрана</p>
                    <p class="right">{{ object.get_type_monitor_display }}</p>
                </div>
                 <div class="info-item">
                    <p class="left" >Кол-во ядер</p>
                    <p class="right">{{ object.count_core }}</p>
                </div>

                 <div class="btns">
                     <p class="price">{{ object.price }} грн</p>
                  <a data-id="{{ object.id }}" data-category = '{{ object.category }}' class="js-add-backet to_backet" href="{% url 'add-to-backet' object.id object.category %}">купить</a>
                    <a href="">
                        <img class="heart-icon" src="{% static 'image/heart.png' %}" alt="">
                    </a>
            </div>

         </div>



            <!--<div class="dostavka">-->
                <!--Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, in!-->
            <!--</div>-->
        </div>
        <div class="desc">
                    <h3 class="left" >Описание</h3>
                    <p class="right">{{ object.desc }}</p>
                </div>

    </div>
<div class="right-filters">
 <!--{% include 'includes/filters.html' %}-->
</div>


{% endif %}


{% block extrascript  %}

<script>
    $(document).ready(function() {
        App.ajax.init();
    });

</script>
{% endblock  %}

eshop/eshop/templates/category/laptop_detail.html
{% extends 'category/index.html' %}

{% block content %}
{% include 'category/item_product.html' with object=object %}
<p class="view-more">З цим товаром також дивляться</p>

<div class="owl-carousel">
    {% for detail in source_detail %}
    <div class="detail-wrap">
        <a href="{% url 'source_detail_item' id=detail.id %}"></a>
        <div class="image">
            <img src="{{ detail.image.url }}" alt="">
        </div>
        <div class="title">{{ detail.title}}</div>
        <div class="desc-item">{{ detail.short_desc }}</div>
        <div class="price-item">{{ detail.price }} грн</div>
    </div>
    {% endfor %}
</div>

{% block extrascript  %}
<script>
    $(document).ready(function () {
        App.products_all.init();
    })
</script>
{% endblock  %}


{% endblock %}

eshop/eshop/templates/category/laptops.html
{% extends 'category/index.html' %}

{% block content %}
{% if req_category %}
<h2>{{ req_category.get_name_display  }}</h2>
{% endif %}
    <h1>{{ title }}</h1>
    <div class="content-wrap">
        <div class="container-flex">
          {% for elem in objects %}
              <a class="item" href="{% url 'laptop-detail' elem.id %}">
                <div class="photo-wrap">
                    {% if elem.image %}
                        <div class="photo-item" style="background-image: url({{elem.image.url}})"></div>
                    {% endif %}
                  </div>
                  <div class="description">
                      <p class='key-text'> Модель: </p>
                      <p class="value-text"> {{ elem.model }}</p>
                  </div>
                  <div class="description">
                      <p class='key-text'> Бренд: </p>
                      <p class="value-text"> {{ elem.brand }}</p>
                  </div>
                  <div class="description">
                      <p class='key-text'> Цена: </p>
                      <p class="value-text"> {{ elem.price }}</p>
                  </div>
              </a>
          {% endfor %}
        </div>
        <!--{% if req_price_to and req_price_from %}-->
            <!--{% include 'includes/filters.html' with all_categories=all_categories  req_price_to=req_price_to  req_price_from=req_price_from %}-->
         <!--{% else  %}-->
                    <!--{% include 'includes/filters.html' with all_categories=all_categories %}-->

        <!--{% endif %}-->
    </div>
{% endblock  %}

eshop/eshop/templates/category/phones.html
{% extends 'category/index.html' %}

{% block content %}
{% if req_category %}
<h2>{{ req_category.get_name_display  }}</h2>

{% endif %}
    <h1>{{ title }}</h1>
    <div class="content-wrap">
        <div class="container-flex">
          {% for elem in objects %}
              <a class="item" href="{% url 'phone-detail' elem.id %}">
                <div class="photo-wrap">
                    {% if elem.image %}
                        <div class="photo-item" style="background-image: url({{elem.image.url}})"></div>
                    {% endif %}
                  </div>
                  <div class="description">
                      <p class='key-text'> Модель: </p>
                      <p class="value-text"> {{ elem.model }}</p>
                  </div>
                  <div class="description">
                      <p class='key-text'> Бренд: </p>
                      <p class="value-text"> {{ elem.brand }}</p>
                  </div>
                  <div class="description">
                      <p class='key-text'> Цена: </p>
                      <p class="value-text"> {{ elem.price }}</p>
                  </div>
              </a>
          {% endfor %}
        </div>
        <!--{% if req_price_to and req_price_from %}-->
            <!--{% include 'includes/filters.html' with all_categories=all_categories  req_price_to=req_price_to  req_price_from=req_price_from %}-->
         <!--{% else  %}-->
                    <!--{% include 'includes/filters.html' with all_categories=all_categories %}-->

        <!--{% endif %}-->
    </div>
{% endblock  %}

{% block extrascript  %}

<script>
    $(document).ready(function() {
        App.ajax.init();
    });

</script>
{% endblock  %}

eshop/eshop/templates/category/search.html
{% block content %}
    {% include 'category/laptops.html' with all_laptops=all_search req_price_to=req_price_to req_price_from=req_price_from %}
{% endblock %}

eshop/eshop/templates/category/source_detail_item.html
{% extends 'category/index.html' %}
{% load static %}
{% block content %}
 <h1>{{ object.title }}</h1>

 <div class="object-item" style="  margin-left: -70px;">
        {% if object.image %}
        <img  src="{{ object.image.url }}" alt="">
        {% endif  %}
        <div class="desc-item-wrap">
            <div class="desc-item">
                {{ object.content|safe }}
            </div>
            <div class="desc-item">

                 <div class="btns">
                     <p class="price">{{ object.price }} грн</p>
                  <a data-id="{{ object.id }}" data-category = '{{ object.category }}' class="js-add-backet to_backet" href="{% url 'add-to-backet' object.id object.category %}">купить</a>
                    <a href="">
                        <img class="heart-icon" src="{% static 'image/heart.png' %}" alt="">
                    </a>
                </div>

         </div>
        </div>
        <div class="desc">
            <h3 class="left" >Описание</h3>
            <p class="right">{{ object.short_desc }}</p>
        </div>

    </div>

{% block extrascript  %}

<script>

$(document).ready(function() {
    App.products_all.init();
})


</script>
{% endblock  %}
{% endblock %}